name: Black-Box Quality Gate - jpteunm.com

on:
  schedule:
    - cron: '0 8 * * 1' # Jalankan setiap Senin jam 08.00 (untuk monitoring berkala)
  workflow_dispatch: # Memungkinkan menjalankan secara manual

jobs:
  quality-assessment:
    runs-on: ubuntu-latest
    env:
      TARGET_URL: 'https://jpteunm.com' # 🎯 URL Target yang ditetapkan

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install test dependencies
      run: |
        pip install -r tests/requirements.txt
        npm install -g @axe-core/cli lighthouse puppeteer

     # 1. TEST PERFORMANCE (ISO 25010: Performance Efficiency)
    - name: Run Lighthouse Performance Test
      id: lighthouse # <-- TAMBAH ID UNTUK STEP INI
      continue-on-error: true # <-- JANGAN BERHENTI MESKI ERROR
      run: |
        lighthouse $TARGET_URL --output=json --output-path=./tests/results/lighthouse-report.json --chrome-flags="--headless --no-sandbox"

    # 2. TEST SECURITY (ISO 25010: Security)
    - name: Run OWASP ZAP Security Scan
      id: zap # <-- TAMBAH ID
      continue-on-error: true # <-- JANGAN BERHENTI MESKI ERROR
      run: |
        docker run -v $(pwd)/tests/results:/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t $TARGET_URL -J zap-report.json || true # Force success

    # 3. TEST ACCESSIBILITY (ISO 25010: Usability)
    - name: Run Accessibility Test
      id: axe # <-- TAMBAH ID
      continue-on-error: true
      run: |
        axe $TARGET_URL --save ./tests/results/accessibility-report.json || echo "Axe failed but continuing..."

    # 4. TEST FUNCTIONALITY (ISO 25010: Functional Suitability)
    - name: Run Basic Functionality Checks
      id: smoke-test # <-- TAMBAH ID
      continue-on-error: true
      run: |
        python tests/blackbox/ui-tests/basic_smoke_test.py || echo "Smoke test failed but continuing..."

    # 5. ANALISIS HASIL & QUALITY GATE
    - name: Analyze results and enforce quality gate
      id: quality-gate
      run: |
        pwd && ls -la
        find . -name "*.json"
        echo "Menjalankan quality gate script..."
        python tests/scripts/quality-gate.py

    # 6. UPLOAD HASIL TES SEBAGAI ARTIFAK (Untuk Inspeksi)
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always() # Upload bahkan jika gagal
      with:
        name: quality-reports
        path: tests/results/

        # 7. [SEMENTARA] SELALU SUKSES, hanya tampilkan hasil
    - name: Show results and always pass (Temporary)
      if: always() # Jalankan step ini bahkan jika step sebelumnya gagal
      run: |
        echo "--- STATUS SEMENTARA ---"
        echo "Lighthouse step status: ${{ steps.lighthouse.outcome }}"
        echo "ZAP step status: ${{ steps.zap.outcome }}"
        echo "Axe step status: ${{ steps.axe.outcome }}"
        echo "Smoke test status: ${{ steps.smoke-test.outcome }}"
        echo "Quality Gate step status: ${{ steps.quality-gate.outcome }}"
        echo "------------------------"
        echo "Script ini sengaja selalu sukses untuk keperluan debugging."
        # Exit code 0 artinya sukses, sehingga pipeline tidak akan gagal

    # 8. KIRIM NOTIFIKASI JIKA SUKSES (Opsional)
    - name: Send success notification
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#monitoring'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
